<?php
return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DB_URL') ?: env('MYSQL_URL'),
            'host' => env('DB_HOST') ?: env('MYSQLHOST', '127.0.0.1'),
            'port' => env('DB_PORT') ?: env('MYSQLPORT', '3306'),
            'database' => env('DB_DATABASE') ?: env('MYSQLDATABASE', 'biswas_performance'),
            'username' => env('DB_USERNAME') ?: env('MYSQLUSER', 'root'),
            'password' => env('DB_PASSWORD') ?: env('MYSQLPASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'biswas_performance'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => env('DB_SSLMODE', 'prefer'),
        ],
    ],
    'migrations' => ['table' => 'migrations', 'update_date_on_publish' => true],
];
